[workspace]
members = ["broker", "cli", "shared", "worker"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.93"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
zmq = "0.10.0"
