[experiment]
image = "docker.io/library/squid-task-example"
out_dir = "./saved_agents"

[nn]
type = "CTRNN"
input_size = 7
hidden_size = 2
output_size = 4
step_size = 0.1

[ga]
population_size = 50
num_generations = 100
elitism_fraction = 0.1
random_fraction = 0.0
selection_fraction = 1.0
mutation_probability = 0.1
mutation_magnitude = 1
init_method = { type = "Random" }
selection_method = { type = "Roulette" }
crossover_probability = 0.5
crossover_method = { type = "Uniform" }
save_every = 10
save_fraction = 0.1

[csv_data]
somedata = ["h1", "h2", "h3"]
