[package]
name = "squid-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
clap.workspace = true
num_cpus = "1.16.0"
shared.workspace = true
zmq.workspace = true
