[package]
name = "squid-broker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
zmq = "0.10.0"
